#!/usr/bin/env python3
"""
Generate a FLUKA LET-moment benchmark case from one SHIELD-HIT12A input case.

Purpose
-------
This script converts one existing SHIELD-HIT12A benchmark case into a matching
FLUKA case directory for the current GETLET / dose-fluence / LET-moment workflow.

It is the case-generator script for folders such as:

    /home/dewh/runs/let_benchmark/fluka_plan02_field01_geoD_mono_letmom

The script starts from a trusted FLUKA template input, then modifies geometry,
source files, scoring setup, and metadata so the generated FLUKA case follows
the corresponding SHIELD-HIT case as closely as possible.

Inputs
------
The script is called with one case name, for example:

    python3 make_fluka_case_from_sh12a_letmom.py plan02_field01_geoD_mono

It expects the original SHIELD-HIT input folder here:

    /home/dewh/2022_DCPT_LET/data/sh12a/input/<case>/

using files such as:

    beam.dat
    mat.dat
    geo.dat
    detect.dat
    sobp.dat

It also copies required FLUKA/source/custom-executable files from:

    /home/dewh/runs/let_benchmark/fluka_geoD_mono/geoD_sobp_step1_smoke.inp
    /home/dewh/au-fluka-tools/myfluka_sobp_pr
    /home/dewh/au-fluka-tools/fluka_sobp_source/source_sampler.f
    /home/dewh/runs/let_benchmark/github_work/2022_DCPT_LET/tools/dewh_fluka/user_routines/fluka_custom_sobp_letmom_titusb_doseflu_fraglet

Outputs
-------
For the selected case, the script creates or updates:

    /home/dewh/runs/let_benchmark/fluka_<case>_letmom/

and writes/copies files including:

    <case>_letmom_step1_smoke.inp
    sobp_original.dat
    sobpcln
    myfluka_sobp_pr
    source_sampler.f
    fluka_custom_sobp_letmom_titusb_doseflu_fraglet

Important caveats
-----------------
1. This script edits FLUKA input text by string replacement and regular
   expressions. Template changes can therefore break assumptions in this script.

2. The generated case should always be checked with a smoke run before being
   trusted for production.

3. This script does not run FLUKA. It only creates the input/case directory.

4. The output case inherits source/spot-list properties from the original
   SHIELD-HIT case. If two SHIELD-HIT sobp.dat files have identical data lines,
   the generated FLUKA source behavior will also be identical.
"""
from pathlib import Path
import shutil
import re
import sys
import hashlib
from datetime import datetime

# -------------------------------------------------------------------------
# Command-line argument and case-folder setup
# -------------------------------------------------------------------------
#
# This generator is intentionally run for one case at a time. That makes it
# easier to inspect each generated FLUKA folder before running production jobs.
if len(sys.argv) != 2:
    print("Usage: python3 make_fluka_case_from_sh12a_letmom.py plan02_field01_geoD_mono")
    sys.exit(1)

# Case name matching a folder under:
#   /home/dewh/2022_DCPT_LET/data/sh12a/input/
#
# Example:
#   plan02_field01_geoD_mono
case = sys.argv[1]

# The current trusted workflow uses the SHIELD-HIT Z_narrow scoring mesh,
# i.e. the central 1 cm × 1 cm scoring channel along depth.
use_znarrow = True

# Original SHIELD-HIT12A input case folder.
repo_case = Path("/home/dewh/2022_DCPT_LET/data/sh12a/input") / case

if not repo_case.exists():
    raise SystemExit(f"Missing SH12A case folder: {repo_case}")

# Output FLUKA work folder for this case.
#
# Example:
#   /home/dewh/runs/let_benchmark/fluka_plan02_field01_geoD_mono_letmom
work = Path("/home/dewh/runs/let_benchmark") / f"fluka_{case}_letmom"
work.mkdir(exist_ok=True)

# -------------------------------------------------------------------------
# Template and auxiliary files copied into the generated FLUKA case folder
# -------------------------------------------------------------------------

# Base FLUKA template input.
#
# This template contains the general geometry/material/scoring structure that
# this script edits to match the requested SHIELD-HIT case.
template = Path("/home/dewh/runs/let_benchmark/fluka_geoD_mono/geoD_sobp_step1_smoke.inp")

# FLUKA SOBP source executable used by the template/source workflow.
source_exe = Path("/home/dewh/au-fluka-tools/myfluka_sobp_pr")

# Fortran source sampler file copied for documentation/reproducibility.
source_f = Path("/home/dewh/au-fluka-tools/fluka_sobp_source/source_sampler.f")

# Current trusted custom FLUKA executable with dose/fluence/GETLET moment scoring.
custom_exe = Path(
    "/home/dewh/runs/let_benchmark/github_work/2022_DCPT_LET/tools/"
    "dewh_fluka/user_routines/fluka_custom_sobp_letmom_titusb_doseflu_fraglet"
)

# Main FLUKA input file generated by this script.
inp_path = work / f"{case}_letmom_step1_smoke.inp"

# Copy the template and required executables/source files into the case folder.
# copy2 preserves timestamps/metadata where possible, which is useful for audits.
shutil.copy2(template, inp_path)
shutil.copy2(source_exe, work / "myfluka_sobp_pr")
shutil.copy2(source_f, work / "source_sampler.f")
shutil.copy2(custom_exe, work / "fluka_custom_sobp_letmom_titusb_doseflu_fraglet")

# Keep an untouched copy of the original SHIELD-HIT spot list for provenance.
shutil.copy2(repo_case / "sobp.dat", work / "sobp_original.dat")

def strip_comment(line):
    """
    Remove an inline SHIELD-HIT comment and surrounding whitespace.

    SHIELD-HIT input files often use `#` for comments. For parsing numerical
    and keyword fields, we only want the part before the comment.
    """

    return line.split("#", 1)[0].strip()


def parse_beam_dat(path):
    """
    Parse the simple key-value structure of SHIELD-HIT `beam.dat`.

    The resulting dictionary maps the first token on each non-comment line to
    the remaining tokens.

    Example structure:
        key -> [value1, value2, ...]

    The exact physics meaning of the entries is handled later when specific
    beam/source parameters are inserted into the FLUKA input.
    """

    data = {}

    for raw in path.read_text().splitlines():
        line = strip_comment(raw)

        # Skip blank lines and SHIELD-HIT-style comment/control lines.
        if not line or line.startswith("*"):
            continue

        parts = line.split()
        key = parts[0]
        vals = parts[1:]

        data[key] = vals

    return data


# Parsed SHIELD-HIT beam definition for the selected case.
beam = parse_beam_dat(repo_case / "beam.dat")

def parse_mat_dat(path):
    """
    Parse SHIELD-HIT `mat.dat` medium blocks for documentation/provenance.

    The generated FLUKA input uses a fixed material mapping for the current
    benchmark workflow, but we still parse the original SHIELD-HIT material file
    so the generated case can record what material definitions were present in
    the source case.

    The function returns a list of dictionaries, one per MEDIUM block:

        {
            "id": material/medium id,
            "comment": inline comment after the MEDIUM line,
            "lines": original material lines inside the block
        }
    """

    media = []
    current = None

    for raw in path.read_text().splitlines():
        stripped = raw.strip()

        if not stripped:
            continue

        # Split each line into the parseable part and optional comment.
        no_comment = stripped.split("#", 1)[0].strip()
        comment = stripped.split("#", 1)[1].strip() if "#" in stripped else ""

        if no_comment.startswith("MEDIUM"):
            # Start of a new SHIELD-HIT material/medium block.
            parts = no_comment.split()
            current = {"id": parts[1], "comment": comment, "lines": []}
            media.append(current)

        elif no_comment == "END":
            # End of the current material/medium block.
            current = None

        elif current is not None:
            # Preserve the original line for the manifest.
            current["lines"].append(stripped)

    return media


# Original SHIELD-HIT material definitions, parsed for manifest output.
mat_media = parse_mat_dat(repo_case / "mat.dat")

# Human-readable material manifest text. This is useful for later audits,
# because the generated FLUKA file otherwise only shows the final mapped FLUKA
# materials, not the original SHIELD-HIT material block content.
mat_manifest_lines = []

for m in mat_media:
    mat_manifest_lines.append(f"MEDIUM {m['id']}: {m['comment']}")

    for line in m["lines"]:
        mat_manifest_lines.append(f"  {line}")

mat_manifest_text = "\n".join(mat_manifest_lines)

def parse_detect_meshes(path):
    """
    Parse geometry mesh definitions from SHIELD-HIT `detect.dat`.

    The benchmark uses SHIELD-HIT detector meshes to define scoring regions.
    For the FLUKA comparison workflow, the most important one is usually:

        Z_narrow

    which corresponds to the central narrow scoring channel along depth.

    This parser extracts mesh names and their X/Y/Z ranges:

        X = (min, max, number_of_bins)
        Y = (min, max, number_of_bins)
        Z = (min, max, number_of_bins)

    and returns a dictionary:

        mesh_name -> mesh_definition
    """

    meshes = {}
    lines = path.read_text().splitlines()
    i = 0

    while i < len(lines):
        # Remove inline comments and whitespace before checking the block type.
        line = lines[i].split("#", 1)[0].strip()

        # We only parse "Geometry Mesh" blocks here.
        if line != "Geometry Mesh":
            i += 1
            continue

        # Start a new mesh block.
        mesh = {"name": None}
        i += 1

        while i < len(lines):
            sub = lines[i].split("#", 1)[0].strip()

            # Blank line ends the current mesh block.
            if not sub:
                i += 1
                break

            # These keywords mark the beginning of another detect.dat block.
            if sub in ("Geometry Mesh", "Filter", "Settings", "Output"):
                break

            parts = sub.split()

            if parts and parts[0] == "Name":
                mesh["name"] = parts[1]

            elif parts and parts[0] in ("X", "Y", "Z") and len(parts) >= 4:
                # Store coordinate limits and number of bins.
                mesh[parts[0]] = (
                    float(parts[1]),
                    float(parts[2]),
                    int(float(parts[3])),
                )

            i += 1

        if mesh.get("name"):
            meshes[mesh["name"]] = mesh

    return meshes


# Detector/scoring meshes from the original SHIELD-HIT case.
detect_meshes = parse_detect_meshes(repo_case / "detect.dat")

# The current workflow uses the Z_narrow mesh as the central depth scoring
# channel. Later code should check/use this object when constructing USRBINs.
zn = detect_meshes.get("Z_narrow")

# Build a human-readable detector mesh manifest for provenance/debugging.
detect_mesh_manifest_lines = []

for name, mesh in detect_meshes.items():
    xs = mesh.get("X", "MISSING")
    ys = mesh.get("Y", "MISSING")
    zs = mesh.get("Z", "MISSING")
    detect_mesh_manifest_lines.append(f"{name}: X={xs}, Y={ys}, Z={zs}")

detect_mesh_manifest_text = "\n".join(detect_mesh_manifest_lines)




# -------------------------------------------------------------------------
# Clean the SHIELD-HIT SOBP spot list for the FLUKA source sampler
# -------------------------------------------------------------------------
#
# The original sobp.dat contains header/comment lines plus spot rows.
# The FLUKA SOBP source sampler expects only spot rows, so we write a cleaned
# copy called `sobpcln`.
#
# Accepted spot rows currently have either:
#   7 columns  = standard spot format used in the current benchmark
#   11 columns = extended format supported by the source workflow
#
# Comment lines beginning with "*" or "#" are excluded.
with open(repo_case / "sobp.dat") as fin, open(work / "sobpcln", "w") as fout:
    for line in fin:
        parts = line.split()

        if len(parts) in (7, 11) and not parts[0].startswith(("*", "#")):
            fout.write(line)


# -------------------------------------------------------------------------
# Read SHIELD-HIT geometry dimensions needed for the FLUKA template
# -------------------------------------------------------------------------
#
# The original SHIELD-HIT geo.dat contains RPP bodies. In the current geometry
# mapping:
#
#   RPP 3 = phantom / solid-water volume
#   RPP 4 = PMMA slab
#
# We use their z-limits to update the FLUKA PHANTOM and SLAB bodies so the
# generated FLUKA geometry follows the selected SHIELD-HIT case.
geo = (repo_case / "geo.dat").read_text().splitlines()

rpps = {}

for line in geo:
    parts = line.split()

    if len(parts) >= 8 and parts[0] == "RPP":
        rpps[parts[1]] = parts

rpp3 = rpps["3"]
rpp4 = rpps["4"]

phantom_zmin = float(rpp3[6])
phantom_zmax = float(rpp3[7])
slab_zmin = float(rpp4[6])
slab_zmax = float(rpp4[7])

# Load the copied FLUKA template input into a string for editing.
#
# From here on, the script modifies the template text and writes it back later.
# This is convenient, but also fragile: if the template formatting changes, the
# regular expressions below may need to be updated.
s = inp_path.read_text()

# -------------------------------------------------------------------------
# Update FLUKA body definitions from SHIELD-HIT geometry
# -------------------------------------------------------------------------
#
# Replace the template PHANTOM z-limits with the z-limits read from SHIELD-HIT
# RPP body 3. The x/y limits stay fixed at [-15, 15] cm for this benchmark.
s = re.sub(
    r"RPP PHANTOM\s+-15\.0\s+15\.0\s+-15\.0\s+15\.0\s+[-0-9.]+\s+[-0-9.]+",
    f"RPP PHANTOM   -15.0   15.0   -15.0   15.0   {phantom_zmin:7.2f} {phantom_zmax:6.2f}",
    s,
)

# Replace the template PMMA slab z-limits with the z-limits read from
# SHIELD-HIT RPP body 4.
s = re.sub(
    r"RPP SLAB\s+-15\.0\s+15\.0\s+-15\.0\s+15\.0\s+[-0-9.]+\s+[-0-9.]+",
    f"RPP SLAB      -15.0   15.0   -15.0   15.0   {slab_zmin:7.2f} {slab_zmax:6.2f}",
    s,
)

# Add a dummy water body far outside the physical simulation geometry.
#
# Purpose:
#   The custom LET scoring routine needs FLUKA built-in WATER to exist as an
#   assigned material so water-reference LET calls are well-defined. The dummy
#   WATEDUM region provides that material assignment without affecting particle
#   transport in the actual phantom.
s = re.sub(
    r"(RPP SLAB\s+-15\.0\s+15\.0\s+-15\.0\s+15\.0\s+[-0-9.]+\s+[-0-9.]+)",
    r"\1\nRPP WATEDUM   200.0  201.0   200.0  201.0   200.0  201.0",
    s,
    count=1,
)

# Exclude the dummy water body from the black-hole region so it can exist as a
# separate FLUKA region.
s = s.replace(
    "BLCKHOLE   5 +BLKHOLE -WORLD",
    "BLCKHOLE   5 +BLKHOLE -WORLD -WATEDUM",
    1,
)

# Add the dummy water region immediately before the END of the region block.
s = s.replace(
    "PMMA       5 +SLAB\nEND",
    "PMMA       5 +SLAB\nWATEDUM    5 +WATEDUM\nEND",
    1,
)

# -------------------------------------------------------------------------
# Replace the template material block
# -------------------------------------------------------------------------
#
# This material block defines the FLUKA materials and assignments used in the
# generated benchmark input.
#
# Important material choices:
#   SOLWATR -> SWF      solid-water phantom material, density 1.032 g/cm^3
#   PMMA    -> PMMA     PMMA slab
#   WATER   -> WATEDUM  dummy water region for water-reference LET
#
# The custom GETLET scoring uses both local-material and water-reference LET.
# The WATEDUM assignment is included so FLUKA built-in WATER is present in the
# material table even though the dummy region is far outside the active geometry.
material_block = """* --- Materials / Assignments ---
MATERIAL         1.0       0.0       1.0       0.0       0.0     1.008HYDROGEN
MATERIAL         6.0       0.0       1.0       0.0       0.0    12.011CARBON
MATERIAL         7.0       0.0       1.0       0.0       0.0    14.007NITROGEN
MATERIAL         8.0       0.0       1.0       0.0       0.0    15.999OXYGEN
MATERIAL        17.0       0.0       1.0       0.0       0.0    35.453CLMAT
MATERIAL        20.0       0.0       1.0       0.0       0.0    40.078CALCIUM

MATERIAL         0.0       0.0     1.032       0.0       0.0      0.0 SOLWATR
COMPOUND   -0.079994  HYDROGEN -0.672956    CARBON -0.023894  NITROGEN SOLWATR
COMPOUND   -0.198689    OXYGEN -0.001383     CLMAT -0.023084   CALCIUM SOLWATR


ASSIGNMA   BLCKHOLE   BLCKHOLE
ASSIGNMA   VACUUM     VAC
ASSIGNMA   AIR        AIR
ASSIGNMA   SOLWATR    SWF
ASSIGNMA   PMMA       PMMA
ASSIGNMA   WATER      WATEDUM
"""

s = re.sub(
    r"\*SETUP MATERIAL COMPOSITION\*.*?\*Biasing, closer to zero WHAT\(2\) => higher chance of collision",
    material_block + "\n*Biasing, closer to zero WHAT(2) => higher chance of collision",
    s,
    flags=re.DOTALL,
)

# -------------------------------------------------------------------------
# Choose the scoring mesh used for the FLUKA USRBIN cards
# -------------------------------------------------------------------------
#
# The trusted comparison workflow uses the SHIELD-HIT Z_narrow detector mesh.
# This is the central narrow scoring channel used for dose, fluence, LET, and
# fragment diagnostics.
#
# Z_narrow is preferred because it matches the SHIELD-HIT benchmark output more
# directly than a full transverse phantom mesh.
if use_znarrow:
    if zn is None:
        raise SystemExit("detect.dat does not define Z_narrow")

    # Mesh limits and bin counts copied from SHIELD-HIT detect.dat.
    xmin, xmax, nx = zn["X"]
    ymin, ymax, ny = zn["Y"]
    zmin_score, zmax_score, nz = zn["Z"]

else:
    # Fallback full-field scoring mesh.
    #
    # This branch is not used in the current trusted workflow, but it is kept as
    # a fallback for debugging or older full-phantom checks.
    xmin, xmax, nx = -15.00, 15.00, 60
    ymin, ymax, ny = -15.00, 15.00, 60
    zmin_score, zmax_score, nz = phantom_zmin, phantom_zmax, 205


# -------------------------------------------------------------------------
# Replace old EDEP/TLEN scoring with GETLET dose/fluence/LET-moment scoring
# -------------------------------------------------------------------------
#
# This block creates the USRBIN scoring cards used by the current trusted
# GETLET workflow.
#
# Important fort-number convention:
#
#   -21 = DOSE_ZN, all-particle dose
#   -22 = PHI_ZN, proton fluence denominator
#   -23 = PAL1_ZN, proton local-material first LET moment
#   -24 = PAL2_ZN, proton local-material second LET moment
#   -25 = PAW1_ZN, proton water-reference first LET moment
#   -26 = PAW2_ZN, proton water-reference second LET moment
#   -27 = PDOSE_ZN, all-proton dose
#   -28 = AFLU_ZN, all-particle fluence
#   -34 = P1DO_ZN, primary-proton dose filtered in COMSCW
#   -29 = P1FL_ZN, primary-proton fluence denominator
#   -30 to -33 = primary-proton LET moments
#   -41 to -47 = charged fragment fluence diagnostics
#
# The post-processing scripts depend on these fort numbers, so changing this
# block requires updating the corresponding parser/mapping scripts.
score_block = f"""USRBIN          10.0     228.0     -21.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      DOSE_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -22.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      PHI_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -23.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      PAL1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -24.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      PAL2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -25.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      PAW1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -26.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      PAW2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     228.0     -27.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      PDOSE_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN    PROTON              PDOS
USRBIN          10.0     228.0     -34.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      P1DO_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -28.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      AFLU_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -29.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      P1FL_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -30.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      P1L1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -31.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      P1L2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -32.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      P1W1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0       1.0     -33.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      P1W2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -41.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      DFLU_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN  DEUTERON              DFLU
USRBIN          10.0     201.0     -42.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      TFLU_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN    TRITON              TFLU
USRBIN          10.0     201.0     -43.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      H3FL_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN  3-HELIUM              H3FL
USRBIN          10.0     201.0     -46.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      H4FL_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN  4-HELIUM              H4FL
USRBIN          10.0     201.0     -47.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      HION_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN  HEAVYION              HION
USRBIN          10.0     201.0     -48.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      L6FL_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -49.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      L7FL_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
* Fragment LET1 scorers for TLET numerator: sum(dl * LET)
USRBIN          10.0     201.0     -50.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      L6L1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -51.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      L7L1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -52.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      D2L1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -53.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      T3L1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -54.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      H3L1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -55.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      H4L1_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
* Fragment LET2 scorers for DLET numerator: sum(dl * LET^2)
USRBIN          10.0     201.0     -56.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      D2L2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -57.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      T3L2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -58.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      H3L2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -59.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      H4L2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -60.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      L6L2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     201.0     -61.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      L7L2_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
* Fragment dose scorers: DOSE, species-filtered
USRBIN          10.0     228.0     -62.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      DODS_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN  DEUTERON              DODS
USRBIN          10.0     228.0     -63.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      TDOS_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN    TRITON              TDOS
USRBIN          10.0     228.0     -64.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      H3DS_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN  3-HELIUM              H3DS
USRBIN          10.0     228.0     -65.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      H4DS_ZN
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
AUXSCORE      USRBIN  4-HELIUM              H4DS
USRBIN          10.0     228.0     -66.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      L6DO_DZ
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USRBIN          10.0     228.0     -67.0      {xmax:.2f}      {ymax:.2f}     {zmax_score:.2f}      L7DO_DZ
USRBIN         {xmin:.2f}     {ymin:.2f}    {zmin_score:.2f}       {float(nx):.1f}       {float(ny):.1f}     {float(nz):.1f}       &
USERWEIG         0.0       0.0       1.0       0.0       0.0       1.0"""

# Replace the old template scoring block with the full GETLET scoring block.
#
# The template originally contained a simpler EDEP/TLEN-style scoring setup.
# This regex replaces that old block with the larger score_block defined above.
#
# Important:
#   The regex depends on the template containing a TLEN_P scorer. If the
#   template scoring section is renamed or reformatted, this replacement should
#   be rechecked.
s = re.sub(
    r"USRBIN.*?TLEN_P\s*.*?USRBIN.*?&\s*",
    score_block + "\n",
    s,
    count=1,
    flags=re.DOTALL,
)

# The step1/smoke input should run quickly, so force START to 10 primaries.
# This file is used only to check that the generated input is structurally valid.
s = re.sub(r"^START.*", "START       10.0", s, flags=re.MULTILINE)

# Write the smoke-test FLUKA input.
inp_path.write_text(s)

# Production statistics are read from SHIELD-HIT beam.dat when available.
# If NSTAT is missing, fall back to 100000 primaries.
nstat = beam.get("NSTAT", ["100000"])[0]

# Create the production input by taking the smoke input and replacing START
# with the requested production number of histories.
prod_path = work / f"{case}_letmom_step2_prod.inp"
prod_s = re.sub(r"^START.*", f"START       {float(nstat):.1f}", s, flags=re.MULTILINE)
prod_path.write_text(prod_s)

# Count the number of cleaned SOBP spots. This is written into the manifest so
# we can audit whether the FLUKA source saw the expected spot list.
nspots = sum(1 for _ in open(work / "sobpcln"))


def sha256(path):
    """
    Compute the SHA256 checksum of a file.

    Checksums are written into CASE_MANIFEST.txt so generated cases can be
    traced back to the exact input/source files used at generation time.
    """

    h = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)

    return h.hexdigest()

manifest = work / "CASE_MANIFEST.txt"
manifest.write_text(f"""# FLUKA case manifest

Generated UTC: {datetime.utcnow().isoformat(timespec='seconds')}Z
Case: {case}

Source SHIELD-HIT folder:
{repo_case}

Generated FLUKA folder:
{work}

Input files and SHA256:
beam.dat   {sha256(repo_case / 'beam.dat') if (repo_case / 'beam.dat').exists() else 'MISSING'}
geo.dat    {sha256(repo_case / 'geo.dat') if (repo_case / 'geo.dat').exists() else 'MISSING'}
mat.dat    {sha256(repo_case / 'mat.dat') if (repo_case / 'mat.dat').exists() else 'MISSING'}
detect.dat {sha256(repo_case / 'detect.dat') if (repo_case / 'detect.dat').exists() else 'MISSING'}
sobp.dat   {sha256(repo_case / 'sobp.dat') if (repo_case / 'sobp.dat').exists() else 'MISSING'}
sobpcln    {sha256(work / 'sobpcln')}

Beam.dat parsed values:
JPART0    {' '.join(beam.get('JPART0', ['MISSING']))}
TMAX0     {' '.join(beam.get('TMAX0', ['MISSING']))}
BEAMSIGMA {' '.join(beam.get('BEAMSIGMA', ['MISSING']))}
BEAMPOS   {' '.join(beam.get('BEAMPOS', ['MISSING']))}
BEAMSAD   {' '.join(beam.get('BEAMSAD', ['MISSING']))}
USECBEAM  {' '.join(beam.get('USECBEAM', ['MISSING']))}
RNDSEED   {' '.join(beam.get('RNDSEED', ['MISSING']))}
NSTAT     {' '.join(beam.get('NSTAT', ['MISSING']))}

Beam.dat physics switches recorded, not one-to-one FLUKA translated:
NEUTRLCUT {' '.join(beam.get('NEUTRLCUT', ['MISSING']))}
DELTAE    {' '.join(beam.get('DELTAE', ['MISSING']))}
DEMIN     {' '.join(beam.get('DEMIN', ['MISSING']))}
STRAGG    {' '.join(beam.get('STRAGG', ['MISSING']))}
MSCAT     {' '.join(beam.get('MSCAT', ['MISSING']))}
NUCRE     {' '.join(beam.get('NUCRE', ['MISSING']))}

Current FLUKA source interpretation:
JPART0=2 interpreted as PROTON
TMAX0 first value interpreted as nominal energy in MeV/u
BEAMPOS copied through the template/source setup
BEAMSAD handled by myfluka_sobp_pr/source_sampler logic
USECBEAM sobp.dat cleaned to sobpcln
NSTAT recorded; smoke input still uses START 10.0

Source sampler:
Executable: myfluka_sobp_pr
Source executable path: {source_exe}
Source Fortran path: {source_f}
Custom LET executable:
Executable: fluka_custom_sobp_letmom_titusb_doseflu_fraglet
Source executable path: {custom_exe}

SOBP:
Cleaned file: sobpcln
Accepted column counts: 7 or 11
Number of accepted beamlet rows: {nspots}

Geometry extracted from geo.dat:
RPP 3 phantom/SWF z range: {phantom_zmin} to {phantom_zmax} cm
RPP 4 slab/PMMA z range: {slab_zmin} to {slab_zmax} cm

SHIELD-HIT mat.dat parsed media:
{mat_manifest_text}

Material mapping used in FLUKA:
MEDIUM 1 / AIR          -> AIR
MEDIUM 2 / Solid water  -> SOLWATR, rho 1.032 g/cm3, H/C/N/O/Cl/Ca composition
MEDIUM 3 / PMMA         -> PMMA
MEDIUM 4 / Water        -> WATER reference material for LET_water context, not assigned to geometry here
MEDIUM 5 / Si           -> SILICON reference material context, not assigned to geometry here
VAC                     -> VACUUM
BLCKHOLE                -> BLCKHOLE

SHIELD-HIT detect.dat parsed meshes:
{detect_mesh_manifest_text}

Scoring:
SHIELD-HIT Z_narrow mesh from detect.dat: {zn}
FLUKA USRBIN DOSE_ZN: all-particle dose, Z_narrow from detect.dat, x={xmin}..{xmax} cm, y={ymin}..{ymax} cm, z={zmin_score}..{zmax_score} cm, nz={nz}
FLUKA USRBIN PDOSE_ZN: all-proton dose, selected by AUXSCORE PROTON
FLUKA USRBIN P1DO_ZN: primary-proton dose, selected in COMSCW by IJ = 1 and LTRACK = 1
FLUKA USRBIN PHI_ZN:  proton track-length fluence moment, sum(ds)
FLUKA USRBIN PAL1_ZN: local-material proton LET moment, sum(ds * LET_local)
FLUKA USRBIN PAL2_ZN: local-material proton LET squared moment, sum(ds * LET_local^2)
FLUKA USRBIN PAW1_ZN: water-reference proton LET moment, sum(ds * LET_water)
FLUKA USRBIN PAW2_ZN: water-reference proton LET squared moment, sum(ds * LET_water^2)

LET reconstruction:
TLET_local = PAL1_ZN / PHI_ZN
DLET_local = PAL2_ZN / PAL1_ZN
TLET_water = PAW1_ZN / PHI_ZN
DLET_water = PAW2_ZN / PAW1_ZN

Stopping power:
L is calculated inside the combined GETLET FLUSCW routine using FLUKA GETLET.
Local-material LET uses MATLET = MEDFLK(NREG,1).
Water-reference LET uses FLUKA built-in WATER assigned to WATEDUM; verify the resulting FLUKA material number after generation.
Run inputs generated:
Smoke input: {inp_path.name}
START smoke: 10.0
Production input: {prod_path.name}
START production from beam.dat NSTAT: {nstat}

Known limitations:
- This generator still patches a FLUKA template.
- beam.dat, mat.dat, and detect.dat are parsed into the manifest; USRBIN mesh values are now taken from detect.dat Z_narrow, but the overall input is still template-patched.
- Geometry currently extracts RPP 3 and RPP 4 specifically; full zone/material table parsing is still future work.
""")


print(f"Created: {work}")
print(f"Smoke input: {inp_path.name}")
print(f"Prod input:  {prod_path.name}")
print(f"Spots:   {nspots}")
print(f"Phantom z: {phantom_zmin} to {phantom_zmax} cm")
print(f"Slab z:    {slab_zmin} to {slab_zmax} cm")
print()
print("Run smoke test with:")
print(f"cd {work}")
print(f"$FLUPRO/bin/rfluka -N 0 -M 1 -e ./fluka_custom_sobp_letmom_titusb_doseflu_fraglet {inp_path.name}")
print("\nRun production with:")
print(f"$FLUPRO/bin/rfluka -N 0 -M 1 -e ./fluka_custom_sobp_letmom_titusb_doseflu_fraglet {prod_path.name}")
